### ISSUE TITLE
How to copy or integrate CSS in the Kiln inscription pages?

### ISSUE THREAD

**Issue by IoannaKy** [kcl-ddh/kiln#15]
I was wondering how to include the ../xsl/global.css in the sample inscription pages. Is this achievable by    adding the CSS as a new link to the base.xsl file, using an <xsl:if> for including it only for /sample/ and /corpus/ pages, or is there another way to include contextual css in Kiln?

Thank you in advance.

**Comment by ajenhl** [comment]
Add the reference to the CSS to a suitable template file in assets/templates. Rather than put logic (determining when to include it and when not), just make or edit a template for the class of pages for which you want that CSS to be present, and associate that template with the pipeline that matches the URLs for those pages.

If you absolutely have to have some logic in there, a Kiln template can make use of xsl:if etc; templates are converted into XSLT by the template processor. The main restriction is that the whole template is converted into a single xsl:template, but that is hardly likely to be relevant in this case.

I hope that helps!
